#!/bin/sh
set -eu

: "${AUTH_SERVICE_HOST:?AUTH_SERVICE_HOST is required}"
: "${AUTH_SERVICE_PORT:?AUTH_SERVICE_PORT is required}"
: "${MEDICAL_IMAGING_SERVICE_HOST:?MEDICAL_IMAGING_SERVICE_HOST is required}"
: "${MEDICAL_IMAGING_SERVICE_PORT:?MEDICAL_IMAGING_SERVICE_PORT is required}"
: "${GATEWAY_HTTP_PORT:?GATEWAY_HTTP_PORT is required}"
: "${GATEWAY_HTTPS_PORT:?GATEWAY_HTTPS_PORT is required}"
: "${GATEWAY_SERVER_NAME:?GATEWAY_SERVER_NAME is required}"
: "${TLS_CERT_PATH:?TLS_CERT_PATH is required}"
: "${TLS_KEY_PATH:?TLS_KEY_PATH is required}"
: "${CORS_ALLOW_ORIGIN:?CORS_ALLOW_ORIGIN is required}"
: "${CORS_ALLOW_CREDENTIALS:?CORS_ALLOW_CREDENTIALS is required}"
: "${AUTH_VALIDATE_PATH:?AUTH_VALIDATE_PATH is required}"
: "${CLIENT_MAX_BODY_SIZE:?CLIENT_MAX_BODY_SIZE is required}"

envsubst '${AUTH_SERVICE_HOST} ${AUTH_SERVICE_PORT} ${MEDICAL_IMAGING_SERVICE_HOST} ${MEDICAL_IMAGING_SERVICE_PORT} ${GATEWAY_HTTP_PORT} ${GATEWAY_HTTPS_PORT} ${GATEWAY_SERVER_NAME} ${TLS_CERT_PATH} ${TLS_KEY_PATH} ${CORS_ALLOW_ORIGIN} ${CORS_ALLOW_CREDENTIALS} ${AUTH_VALIDATE_PATH} ${CLIENT_MAX_BODY_SIZE}' \
  < /etc/nginx/templates/nginx.conf.template \
  > /etc/nginx/nginx.conf

exec nginx -g 'daemon off;'
